### PR TITLE
STR-141 -- FE: Create Multi-Question text-input (1-100) Quiz Slide + Answer Slide template

### PR DESCRIPTION
**Pull request by frlzjosh**
# Description
  To create the Multi-Question text-input (1-100) Quiz Slide + Answer Slide template

# Testing
'What does the reviewer need to do to test your PR?'

### Preparations for testing
1. Run `yarn watch`.
2. Update **`Module.vue`** to reflect the snippet below for testing the template.
```
<template>
  <div ref="moduleContainer" :class="checkWindowWidth">
    <Navbar></Navbar>
    <module-header :size_of_container="sizeOfContainer"></module-header>
    <quiz-input-template v-if="slideNumber !== 2 && slide_type=== 'quizInput'"></quiz-input-template>
    <pie-chart-template v-if="slideNumber === 2"></pie-chart-template>
    <module-footer></module-footer>
  </div>
</template>
```

### Testing Functionality
1. Login as `april.feldman` or `cyndee.bellamy`.
2. In the **Dashboard**, visit the **Alcohol** module.
3. Attempt to break form validation and ensure all requirements are met to be able to continue.

>- Numeric Values
>- Range of ***0-100***
>- Positive Integers
>- All inputs filled to continue
>- All inputs valid
>- Invalid inputs remove continue even if continue was allowed previously

4. Enter valid inputs and click continue.
5. Check pie charts properly present data side by side from what the **user** said against what **they** said.
 5. Make sure the code is fire; pour one for Josh who did 99% of the code and didn't get to see it pushed up on dev.

# Installation
Run ***`yarn install`***

### CODE REVIEW

**Review by andrewMETALAB — DISMISSED** [review]
- if possible, remove tooltip that appears when hovering over the pie charts
- instead of pressing TAB to go from question-page to results-page, make it so the user must press "continue" button
- Please add headers above each pie chart that say "You said:" for left pie chart and "Survey Results:" for right pie chart (see mockup)

**Review by andrewMETALAB — DISMISSED** [review]
ok, this is looking REALLY good. A couple of minor things:

(1) could you please keep the colors consistent between the left pie chart and the right pie chart? (make them both blue/gray) 

(2) If the user enters a negative number, an error message appears ("Your response must range from: 0 - 100"). This is great. Can we make it so that this error message ALSO appears if: 
- the user enters a number GREATER than 100
- the user enters a letter or character

(3) I was able to break validation in one specific instance. I'm not TOO worried about it, but it would be ideal if we could prevent this from occurring:
`enter a VALID value on all 4 inputs. The continue button becomes enabled (good). Then change one of the inputs to from a VALID number to a character such as "a". Note how the continue button is still enabled. It should not be.`

**Review by JaimeGG64 — APPROVED** [review]
💵

**Review by zerv-dev — APPROVED** [review]
👍

**Pull request merged**
