### PR TITLE
STR-129 -- FE: Create single question multiple choice slide template

### PR DESCRIPTION
**Pull request by frlzjosh**
# Description
'Write a meaningful description of your 
There exists a template that reflects the single question multiple choice slides.
Should include styling as well as the functionality
Should be mobile responsive
# Testing
'What does the reviewer need to do to test your PR?'
1. Login as `apirl.feldman`
2. Click on any module
3. Make sure that the "continue" button doesn't appear
3. Select anything to see the functionality such as styling that displays the wrong and right answer
4. Click continue to see that the icons and styling disappear and that the continue button itself disappears

# Installation
'Are there any dependencies the reviewer needs to download?'

### CODE REVIEW

**Review by ekno27 — DISMISSED** [review]
1. Move quiz-template component onto content.vue
2.  Whenever a user picks a choice, make sure they are unable to pick any others, regardless of whther they got it right or wrong
3. add a quick transition so that when we let the user know the correct answers, the icon appearance isn't as jerky n sudden. You might be able to use something along the lines of the ``transition-350ms`` class
4. create tests for the new vuex elements
5. there seems to be a lack of styling on the continue button when in mobile view
6. Text should be blue, according to the mockup

**Review by andrewMETALAB — DISMISSED** [review]
(1) on mobile, the bottom of the last option gets cut off. Let's add some padding to the bottom of the page to account for this

(2) it's possible that the "wrong answer message" will be longer than 1 line. Let's take that into account. (Right now, the text gets cut-off if that message is longer than 1 line).  To accomplish this, you'll probably have to use `min-height` instead of explicitly setting a `height`. You might then struggle with getting the blue bar on the left to be full-height. To handle that, you might want to either utilize flexbox (will probably require changing the DOM structure slightly) or use a left-border to create that blue bar and then use `position: absolute` on the "x".

**Comment by andrewMETALAB** [comment]
A couple more requests after reviewing with Tiffany:

(a) instead of setting explicit height and width of the quiz-item-box, lets set the width to be 100% and the height to auto. Then place them in a `col-sm-5` instead of `col-sm-6`. 
(b) Set the image height to auto and set the image width to be 90% (so that its size is relative to it's container) 
(c) lets set the font-size to 1rem instead of .85rem 👍 
(d) lets make sure the navbar is still at the top of each template (i understand that this might be done in a different task)

THANK YOU SIR

**Review by andrewMETALAB — DISMISSED** [review]
Ok a couple minor things:

(1) Does that div need a class of "module-quiz__option" AND "module-quiz__option--img"? Or can those 2 classes be merged into 1 class??

(2) Looks like there is some CSS in a media query that's can be deleted (its being overwritten at all times so just remove it). It's this: 
`.module-quiz__option {
    height: 7.5rem;
    width: 18.5rem;
}`

(3) If you set that "module-quiz__option" div to `height: 100%` instead of `height:auto`, then all of the boxes will have equal height (to make the appearance a little more aesthetically pleasing). But you'll have to add some margin-bottom to each "col-sm-5" wrapper div. I think it would be good to do this.

**Review by andrewMETALAB — DISMISSED** [review]
ok ALMOST THERE, 2 TINY things!

(1) the div with a class of `module` has that class repeated twice - remove one of them!
(2) that class of `module` has some `padding-bottom` on small screens to account for the sticky-footer. This works great in chrome but not in firefox. If you change it from `padding-bottom` to `margin-bottom` then it will work in both firefox and chrome 👍

**Review by andrewMETALAB — APPROVED** [review]
GREAT WORK, APPROVED! 👍

**Comment by BrianLinggadjaja** [comment]
Just one small thing when clicking on each answer and continue button. The left bar indicator should stay persistent.

**Comment by ekno27** [comment]
When user goes back and tries to access the slide again, user cannot interact with the options. Also, if the user gets the option wrong, is the user shown the correct answer as well?

**Comment by andrewMETALAB** [comment]
> When user goes back and tries to access the slide again, user cannot interact with the options. Also, if the user gets the option wrong, is the user shown the correct answer as well?

Good thinking. 

After the user clicks on one of the answers (whether it's correct or incorrect):
(1) the "continue" button should become enabled
(2) the user should still be able to click on other answers. (removing the 'active' state from their original selection and adding the 'active' state to the newly clicked answer).

#1 is already complete but #2 needs to be implemented. Sorry for the confusion and for not letting you know of this specification earlier. Let me know if more clarification is needed on this. Thank you.

**Review by BrianLinggadjaja — APPROVED** [review]
👍

**Pull request merged**
