### PR TITLE
STR-68 -- FE: Create a generic Module Page

### PR DESCRIPTION
**Pull request by frlzjosh**
# Description
'Write a meaningful description of your task'
  - includes next and back buttons, as well as any other functionality that is required by the module page 
  - should be a view that wraps all possible "pages" (not web pages) of content inside for the current 
  - "MOBILE RESPONSIVENESS IS important"
  - Style progress bar
# Testing
'What does the reviewer need to do to test your PR?'
  - 1. Login as `april.feldman`
  - 2. Click on the Alcohol module to see the module page
     - Make sure it is mobile responsive
     - look at my sass and bem to make sure it is good
     - compare to mock up to assure that it is similar
# Installation
'Are there any dependencies the reviewer needs to download?'
  - if you have not ran `yarn install` in a while (1 month) then you will need to.

### CODE REVIEW

**Review by liadGolan — DISMISSED** [review]
There is horizontal scrolling present in the generic module page

**Review by BrianLinggadjaja — APPROVED** [review]
👍

**Review by Tiffufu — DISMISSED** [review]
I slacked you the screenshots of the most up to date wireframe templates. Please make changes to reflect the latest wireframe. Thank you!

**Review by andrewMETALAB — APPROVED** [review]
well done 👍 👍 👍 👍

**Pull request merged**
