### PR TITLE
STR-162 -- FE: Fix bug when going back to intro slide, the next slides wont be able to continue

### PR DESCRIPTION
**Pull request by BrianLinggadjaja**
# Description
Fixed navigation functionality, revisited the core of the application.
  
# General Testing
1. Login as `cyndee.bellamy` or `april.feldman`.
2. Visit the alcohol module.
3. Ensure all module content works.
4. Make sure you can go (back) and (forward) with the navigation controls seamlessly.
5. Make progress on a few slides, visit dashboard; make sure it puts your progress off where you started **did not implement the api yet, testing the state***

# Testing Button Events
Check for the following button events
1. First slide is always continueable
2. Info slides are enabled after 8 seconds
3. Video slides, continue button is enabled after video finished
4. Card flip slides, continue after all cards are flipped.
5. Last slide **(continue)** has been replaced to **(return to dashboard)**.

### CODE REVIEW

**Review by andrewMETALAB — APPROVED** [review]
Well done. I stress tested the app and could not produce any errors or issues.  👍

**Review by zerv-dev — APPROVED** [review]
👍

**Review by JaimeGG64 — APPROVED** [review]
💵

**Review by luisjg — APPROVED** [review]
👍

**Pull request merged**
