### PR TITLE
STR-18 -- FE: Create Splash Page for Intervention Group

### PR DESCRIPTION
**Pull request by BrianLinggadjaja**
# Description
Created an intervention group view and route.
  
# Testing
1. Visit the route /interventiongroup and ensure "Intervention Group" shows up.

### CODE REVIEW

**Review by andrewMETALAB — APPROVED** [review]

**Review by liadGolan — DISMISSED** [review]
Should be using the title-ing established in STR-39

**Comment by BrianLinggadjaja** [comment]
Holding off until login is done so we can have the same **_/dashboard_** route for all the groups. Dependent on login to pass route data for each group.

**Comment by BrianLinggadjaja** [comment]
This task is ready to be pushed up; decided to change route path in STR-21 instead.

**Review by liadGolan — APPROVED** [review]
👍

**Pull request merged**
