### PR TITLE
STR-37 -- FE: Create Calendar page with "dummy" items listed  (The skeleton for a list)

### PR DESCRIPTION
**Pull request by BrianLinggadjaja**
# Description
Created calendar module based off mock-up.
  
# Testing
1. Log in as steve.
2. Visit the /schedule route. **_Implemented for testing purposes_**.
3. Ensure the calendar meets the original mock-up design.

### CODE REVIEW

**Review by frlzjosh — APPROVED** [review]
great job man!

**Review by frlzjosh — COMMENTED** [review]
Really fast changes:
1. it seems as if on the mock-up that the font-color is supposed to be a dark blue
2. on mobile with a width of 375px (being iphone 6/7/8), the dates collapse and the component is no longer responsive
3. There needs to be a little more padding between the "Schedule" and the text underneath
4. Finally there needs be less margin space on the container. `1.3rem` seems to do the trick

**Review by mbendandour — DISMISSED** [review]
USING MAMP: When I try to log in, the url route collapses from **localhost/istart/public/login** to **localhost/login**
so I can't review this task

**Review by andrewMETALAB — DISMISSED** [review]
Great work. A couple thoughts below. You can refute these if you disagree. 
(1) Do you think the "schedule-description" block could be modularized and re-used? (Basically rename it to "page-description" so that we can use it on other pages as well)?
(2) You have lots of classes that are just applying one css rule (text-align: right). I think you should  replace them with bootstrap's "text-right" class.
(3) You kind of created a new, unique container with the "schedule-container" class. Seems that its intended to only be used on this page. It will be weird & inconsistent if all of the other pages have a different size container.

**Review by andrewMETALAB — APPROVED** [review]
perfect 👍

**Pull request merged**
