### PR TITLE
STR-59 -- FE: Ensure all front-end code conforms to our current naming convention we agreed upon.

### PR DESCRIPTION
**Pull request by ekno27**
# Description
changed files and directory names to fit the structure we determined with the front end
  
# Testing
1. check that every part of the application works as intended
2. run jest
3. rejoice in the fact that even though we did not have an official convention until recently we still stayed consistent and organized

# Installation
non

### CODE REVIEW

**Review by andrewMETALAB — COMMENTED** [review]
Immana let ya'll handle this one. No mentor approval needed. 👍

**Review by BrianLinggadjaja — DISMISSED** [review]
When we are importing in files, a few vanilla JS file import names are inconsistent. Some places where this is occurring is in ***`router.js`*** .

**Review by frlzjosh — CHANGES_REQUESTED** [review]
it's good. make sure to merge dev

**Review by BrianLinggadjaja — APPROVED** [review]
👍

**Review by frlzjosh — APPROVED** [review]

**Pull request merged**
