### PR TITLE
STR-110 -- BE: Email about group is sent out on every log in, not when the user is assigned to the group

### PR DESCRIPTION
**Pull request by liadGolan**
# Description

THIS TASK IS DONE WHEN:

Emails are no longer being sent on every log in, only when a user is being assigned to a group
  
# Testing
1. Log in as any user besides steve
2. Notice that no email is being sent
3. Rejoice

### CODE REVIEW

**Review by luisjg — APPROVED** [review]
👍

**Comment by BrianLinggadjaja** [comment]
It's a shame we are removing this feature, I wish we could just hard code liad's email.

**Review by frlzjosh — CHANGES_REQUESTED** [review]
Could not login. Threw a 500 error when attempting to login.
1 ) Attempt to merge dev again and accept the participant stuff instead of the research stuff.

**Review by mbendandour — APPROVED** [review]

**Review by frlzjosh — APPROVED** [review]
nice!

**Pull request merged**
