### PR TITLE
STR-51 -- FE: Setup Jest Extended 

### PR DESCRIPTION
**Pull request by BrianLinggadjaja**
# Description
Added jest-extended to our yarn packages; removed package-lock.json (used for npm not yarn); imported jest-extended to current jest test file; added alias for yarn test:unit to yarn jest-unit; added jest cache clear command which is yarn jest-cacheClear .
 
# Testing
1. Do a **`yarn install`** to download jest-extended.
1. Run **`yarn jest-unit`** and ensure there is no errors or failure.
2. If you have a caching issue/error run **`yarn jest-cacheClear`**.

### CODE REVIEW

**Comment by BrianLinggadjaja** [comment]
This is waiting on login so I can import jest-extended in the proper structure

**Review by andrewMETALAB — DISMISSED** [review]
I tried following your directions, but I'm confused:
(1) where can I find `.toMatch(msg)` in order to replace it, per your step #2 ?
(2) there doesnt seem to be a command called `yarn jest-test`, per your step #3. Did you mean `jest-unit`??

**Comment by BrianLinggadjaja** [comment]
> I tried following your directions, but I'm confused:
> (1) where can I find `.toMatch(msg)` in order to replace it, per your step #2 ?
> (2) there doesnt seem to be a command called `yarn jest-test`, per your step #3. Did you mean `jest-unit`??

You are indeed correct, it is yarn jest-unit. I fixed the description, the reason you didn't see .toMatch() was because I merged the most recent dev and it removed it. I instead just implemented a test using jest-extended.

**Review by andrewMETALAB — COMMENTED** [review]
ok that makes sense brian.
I'm getting this error when running `yarn jest-unit`: `Cannot find module 'jest-extended'`
Is that to be expected??

**Review by andrewMETALAB — APPROVED** [review]
👍

**Review by liadGolan — APPROVED** [review]
👍

**Pull request merged**
